version: "3.7"
services:
  bookstore:
    image: tomcat
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == manager]	  
    ports:
      - "8000:8080"
    volumes:
      - ./context.xml:/usr/local/tomcat/webapps/manager/META-INF/
      - ./tomcat-users.xml:/usr/local/tomcat/
      - ./target/bookstore.war:/usr/local/tomcat/
    expose:
      - 8080
    networks:
      - webnet

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bookstore
      MYSQL_USER: atul
      MYSQL_PASSWORD: atul
    ports:
      - "3306:3306"
    volumes:
      - ./sql/bookstore.sql:/docker-entrypoint-initdb.d
    expose:
      - 3306
    deploy:
      placement:
        constraints: [node.role == worker]	  
    networks:
      - webnet
 
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == worker]
    networks:
      - webnet	  
  
  networks:
    webnet:
      driver: overlay
